### PR TITLE
Update to Angular 9

### PR DESCRIPTION
**Pull request by fredjammes**

### CODE REVIEW

**Comment by dudendy** [comment]
Someone tried use this with Angular 9?

**Comment by chloroplast11** [comment]
Hello I tried to upgraded to Angular 9, and something was wrong with ng-pick-datetime-moment when I ran my application.

```
ERROR in ../ng-pick-datetime-moment/moment-adapter/moment-date-time.module.ts(22,2): Error during template compile of 'OwlMomentDateTimeModule'
  Function calls are not supported in decorators but 'ɵmakeDecorator' was called in 'NgModule'
    'NgModule' calls 'ɵmakeDecorator'.
```

Do you plan to updated this package?

**Comment by fredjammes** [comment]
I do ^^

**Comment by fredjammes** [comment]
I only tried with the builtin app in the package, it might not be enough...
Yet, I can't reproduce the error @chloroplast11 have

**Comment by cannontechnology** [comment]
Check out https://github.com/danielmoncada/date-time-picker

**Pull request closed without merging**
