### PR TITLE
Adding name tag to input on popup

### PR DESCRIPTION
**Pull request by maenthoven**
Fixes missing name exception triggered by Angular

### CODE REVIEW

**Comment by DanielYKPan** [comment]
What's the name tag for?

**Comment by maenthoven** [comment]
If the input tag ends up in a form tag, angular will throw a Missing Name
exception.

Adding the name tag prevents this exception.

**Comment by DanielYKPan** [comment]
The picker is added into the view after the form is initial, so it should be a problem. Did you try it in a form and have a error or warning?

**Comment by maenthoven** [comment]
I'm using it in a component that's an entryComponent in the module (used
with ngbmodal).

I get the above mentioned error when doing it this way.

**Comment by DanielYKPan** [comment]
Could you use [StackBlitz](https://stackblitz.com/) to build app and show the issue you mention about?

**Comment by maenthoven** [comment]
Erm, I was just working on the StackBlitz...

This is absolutely an error with your modal. It's going to occur any time someone includes the app datetime picker inside a component that's loaded in entryComponents

**Comment by DanielYKPan** [comment]
I tested it in a entryComponent, and it worked fine.
So please use [StackBlitz](https://stackblitz.com/) to build app and show the issue

**Pull request closed without merging**
