### PR TITLE
Allow configuring the increment for minutes

### LINKED ISSUE #95: missing step attribute for time sliders
I just upgraded to version 4.3.0 from version 4.0.5.  In version 4.0.5, time-panel.component.js had capability to set a [step] attribute for time sliders.  It defaulted to 1 so the minute slider would be for every value between 0 and 59.  I manually modified the [step] attribute value to 5 so the slider for minutes would be every 5 minutes (0 - 59 but every 5 minute increment).  I do not need minute precision.  Is it possible to add [step] attribute back and surface it to optional attribute values please?  Thanks.

### PR DESCRIPTION
**Pull request by culli**
This could resolve #95 (in 5.x)

### CODE REVIEW

**Comment by DanielYKPan** [comment]
@culli 
I don't think this is necessary in version 5.
Because you could directly change the hour, minute or second value on their inputs. So if you don't want to increase or decrease value by 1, you could type the value in their inputs.

**Comment by culli** [comment]
Yes you can type in the value.  But why not have the option?  There are 4 people asking for it already and editing the source code to do it (see issue #95).  @tomschreck @jhhoff2 @antb-developer and myself.  Hopefully they'll comment here too.

In my case, I'm building an app that includes some basic calendaring and the users are interested in meetings in increments of 15 minutes, so most entries are going to using this step function.

**Comment by stan-radu-andrei** [comment]
How can i install this? i already have 5.0.0-beta.11

**Comment by culli** [comment]
@stan-radu-andrei The PR has not been accepted yet, so you'd have to do your own build and merge my branch in.

**Comment by y4nnick** [comment]
+1 on this one!

**Comment by DanielYKPan** [comment]
check the version 5.1.*.
It has been added.

**Pull request closed without merging**
