### PR TITLE
Fixes #552 and Angular 8

### LINKED ISSUE #552: Datepicker not work for angular 7 SSR
As mentioned on npm this datepicker is for angular 6+.Here 6+ means above angular 6.I am now using angular 7.1.1 and date picker version is -  

`  "ng-pick-datetime": "^7.0.0",
    "@angular/core": "^7.1.2",
`
**

 It gives the following problem after creating the build and running on node server-

**
```
/home/omkar/Workspace/Angular7/dist/server.js:258752
        __metadata("design:paramtypes", [Event]),
                                         ^

ReferenceError: Event is not defined

```

### PR DESCRIPTION
**Pull request by pasevin**
This is a working merged update based on the pull request: https://github.com/DanielYKPan/date-time-picker/pull/536 https://github.com/DanielYKPan/date-time-picker/pull/535 plus my fix related to the issue with webpack-cli and barrel imports.

I've tested this extensively, and am using on production.

### CODE REVIEW

**Comment by Grant-Visser** [comment]
Is there any news on this?

**Comment by tanganellilore** [comment]
@danielYKPan, do you have some news with this merge?

**Comment by ThePatzen** [comment]
Waiting for this :-)

**Comment by tanganellilore** [comment]
Any chance for this merge?

**Comment by pasevin** [comment]
@DanielYKPan can you look at this?

**Comment by circularone** [comment]
Can this please be merged?

**Comment by pasevin** [comment]
Added Angular 8 support

**Comment by Amaury-T** [comment]
Hello @DanielYKPan, you have merged this branch on master but there is no new version on npm, do you plan it ? :)
Waiting for angular 8 support for my project :)

**Comment by petemcwilliams** [comment]
> Hello @DanielYKPan, you have merged this branch on master but there is no new version on npm, do you plan it ? :)
> Waiting for angular 8 support for my project :)

I am still using npm i ng-pick-datetimex, would like to move back to proper npm release.

**Pull request merged**
